'''
Homework(ladder.py):
讓使用者輸入梯形的上底、下底及高，程式會計算梯形的面積(上底加下底乘以高除以2)
'''
top=int(input('請給我梯形的上底'))
buttom=int(input('請給我梯形的下底'))
heigh=int(input('請給我梯形的高'))
print('梯形的上底',top)
print('梯形的下底',buttom)
print('梯形的高',heigh)
x=(top+buttom)*heigh/2
print('梯形的面積',x)

'''
Homework(circle_s.py)
使用者輸入圓柱體的半徑及高，程式會計算圓柱體的體積
圓柱體體積的公式為「圓週率乘以半徑平方再乘以高」。
'''
a=int(input('請給我圓柱體的半徑'))
b=int(input('請給我圓柱體的高'))
pi=3.14
y=pi*a**2*b
print('圓柱體的半徑',a)
print('圓柱體的高',b)
print('圓柱體的體積',y)